#!/bin/sh

set -eux

debian/rules clean > "${AUTOPKGTEST_ARTIFACTS}/${SUFFIX}_auto_clean.log"
dh_update_autotools_config > "${AUTOPKGTEST_ARTIFACTS}/${SUFFIX}_autotools_config.log"
dh_autoreconf > "${AUTOPKGTEST_ARTIFACTS}/${SUFFIX}_autorefconf.log"
debian/rules override_dh_auto_configure > "${AUTOPKGTEST_ARTIFACTS}/${SUFFIX}_auto_configure.log"
debian/rules override_dh_auto_build > "${AUTOPKGTEST_ARTIFACTS}/${SUFFIX}_auto_build.log"
debian/rules override_dh_auto_test
