#!/bin/sh
set -e

# Building curl is required because libauthretry (from "make test") requires
# libcurl.
#
# It might be possible to patch the makefile to have libauthretry link against
# the system's installed libcurl, patches welcome.
#
# gnutls tests run against the built curl and libcurl rather than the installed
# one as we don't ship a curl linked against gnutls (only gnutls libraries).


export DEB_BUILD_PROFILES="pkg.curl.gnutls-only"
export VERBOSE=1

# Don't skip tests which fail on ipv6-only environments for autopkgtests.
# I'm not aware of runners with this configuration for debci, and a retry
# should be easy enough it it happens.
# References:
# https://bugs.debian.org/1032343
# https://github.com/curl/curl/issues/10682
export TESTS_FAILS_ON_IPV6_ONLY_MACHINES=""

# Suffix used to name build log files for this specific test scenario
export SUFFIX="gnutls"

. debian/tests/common-upstream-tests
